mybatis:
  type-aliases-package: com.antonio.example.springtddmybatis.model
  mapper-locations: classpath*:**/mappers/*Mapper.xml

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: