CREATE SEQUENCE PERSON_ID_SEQ;

CREATE TABLE PERSON (
    ID          BIGINT DEFAULT PERSON_ID_SEQ.NEXTVAL PRIMARY KEY,
    CPF         VARCHAR(11)   NOT NULL,
    NAME        VARCHAR(80)   NOT NULL
);