CREATE SEQUENCE ADDRESS_ID_SEQ;

CREATE TABLE ADDRESS (
    ID          BIGINT DEFAULT ADDRESS_ID_SEQ.NEXTVAL PRIMARY KEY,
    STREET       VARCHAR(255)  NOT NULL,
    NUMBER       INT           NOT NULL,
    COMPLEMENT   VARCHAR(255)  NOT NULL,
    NEIGHBORHOOD VARCHAR(255)  NOT NULL,
    CITY         VARCHAR(255)  NOT NULL,
    STATE        VARCHAR(2)    NOT NULL,
    PERSON_ID    BIGINT SERIAL NOT NULL,
    FOREIGN KEY  (PERSON_ID) REFERENCES PERSON(ID)
);

