DELETE FROM telephone;
DELETE FROM address;
DELETE FROM person;

ALTER SEQUENCE TELEPHONE_ID_SEQ RESTART WITH 1;
ALTER SEQUENCE ADDRESS_ID_SEQ RESTART WITH 1;
ALTER SEQUENCE PERSON_ID_SEQ RESTART WITH 1;